user = "solana"

[gossip]
    entrypoints = [
      "entrypoint.testnet.solana.com:8001",
      "entrypoint2.testnet.solana.com:8001",
      "entrypoint3.testnet.solana.com:8001",
    ]

[consensus]
    identity_path = "/solana/validator_identity.json"
    vote_account_path = "/solana/vote_account.json"
    known_validators = [
        "7heQNXEtxSv3wV8sNbuQsDN5xNGbbpLvHGiyXuJxEf7n",
        "ESgP63knYThVSNWcwgwzA8cnh2MnUf6SaCWpnC8mrkn3",
        "2Nnw9RZvT2qeKq74rkw8hWDJZUDSKxiBarmQMFxHzzCt",
        "J7v9ndmcoBuo9to2MnHegLnBkC9x3SAVbQBJo5MMJrN1",
        "2CY8VXH2jummjSmwcusSj2jGMiaHE4eo7WQ9LScxykvt",
        "5D1fNXzvv5NjV1ysLjirC4WY92RNsVH18vjmcszZd8on",
        "dDzy5SR3AXdYWVqbDEkVFdvSPCtS9ihF5kJkHCtXoFs",
        "Ft5fbkqNa76vnsjYNwjDZUXoTWpP7VYm3mtsaQckQADN",
        "eoKpUABi59aT4rR9HGS3LcMecfut9x7zJyodWWP43YQ",
        "9QxCLckBiJc783jnMvXZubK4wH86Eqqvashtrwvcsgkv",
    ]

[rpc]
    port = 1100
    full_api = false
    private = true

[reporting]
    solana_metrics_config = "host=https://metrics.solana.com:8086,db=tds,u=testnet_write,p=c4fa841aa918bf8274e3e2a44d77568d9861b3ea"

[ledger]
    path = "/solana/ledger"
    accounts_path = "/solana/accounts"
    limit_size = 50_000_000

[snapshots]
    path = "/solana/snapshots"

[tiles]
    [tiles.gui]
        # If the GUI is enabled.
        #
        # Names and icons of peer validators will not be displayed in
        # the GUI unless the program-id index is enabled, which can be
        # done by setting
        #
        # [ledger]
        #   account_indexes = ["program-id"]
        #
        # In your configuration above.
        # for some reason, gui can't bind to the port it wants to... maybe nginx? dunno
        enabled = true

        # The address to listen on.  By default, if enabled, the GUI
        # will only be accessible from the local machine.  If you wish
        # to expose it to the network, you can change the listen
        # address.
        #
        # The Firedancer team makes a best effort to secure the GUI
        # endpoint but exposing it to the internet from a production
        # validator is not recommended as it increases the attack
        # surface of the validator.
        gui_listen_address = "0.0.0.0"

        # The port to listen on.
        gui_listen_port = 80

[layout]
    affinity = "1-24"
    agave_affinity = "25-35,37-38,40-47"
    net_tile_count = 1
    quic_tile_count = 2
    resolv_tile_count = 1
    verify_tile_count = 4
    bank_tile_count = 2
    shred_tile_count = 3

[tiles.bundle]
    enabled = true
    url = "https://testnet.block-engine.jito.wtf"
    tip_distribution_program_addr = "F2Zu7QZiTYUhPd7u9ukRVwxh7B71oA3NMJcHuCHc29P2"
    tip_payment_program_addr = "GJHtFqM9agxPmkeKjHny6qiRKrXZALvvFGiKf11QE7hy"
    tip_distribution_authority = "GZctHpWXmsZC1YHACTGGcHhYxjdRqQvTpYkb9LMvxDib"
    commission_bps = 10000
